version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - '27017:27017'
  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    ports:
      - '6379:6379'
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
  worker:
    container_name: worker
    build: ./src
    hostname: worker
    command: |
      celery -A app.workers.worker worker -l info
    volumes:
      - ./src/:/usr/src/app/
    depends_on:
      - redis
      - rabbitmq
      - mongodb
  scheduler:
    container_name: scheduler
    build: ./src
    hostname: scheduler
    command: |
       celery  -A app.workers.worker beat
    volumes:
      - ./src/:/usr/src/app/
    depends_on:
      - redis
      - rabbitmq
  web:
    container_name: web
    build: ./src
    command: |
      uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - worker
      - scheduler
      - mongodb