version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - '27017:27017'
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
